import { Routes, Route } from "react-router";
import Dashboard from "@pages/dashboards";
import Default from "@pages/user/publicProfiles/profiles/default"
import Creator from "@pages/user/publicProfiles/profiles/creator"
import Company from "@pages/user/publicProfiles/profiles/company"
import NFT from "@pages/user/publicProfiles/profiles/nft"
import Blogger from "@pages/user/publicProfiles/profiles/blogger"
import CRM from "@pages/user/publicProfiles/profiles/crm"
import Gamer from "@pages/user/publicProfiles/profiles/gamer"
import Feeds from "@pages/user/publicProfiles/profiles/feeds"
import Plain from "@pages/user/publicProfiles/profiles/plain"
import Modal from "@pages/user/publicProfiles/profiles/modal"
import Works from "@pages/user/publicProfiles/works"
import Teams from "@pages/user/publicProfiles/teams"
import Network from "@pages/user/publicProfiles/network"
import Activity from "@pages/user/publicProfiles/activity"
import Campaigns from "@pages/user/publicProfiles/campaigns"
import ThreeColumns from "@pages/user/publicProfiles/projects/threeColumns"
import TwoColumns from "@pages/user/publicProfiles/projects/twoColumns"
import Empty from '@pages/user/publicProfiles/empty'
import GetStarted from '@pages/user/myAccount/accountHome/started'
import UserProfile from '@pages/user/myAccount/accountHome/userProfile'
import CompanyProfile from '@pages/user/myAccount/accountHome/companyProfile'
import SettingSidebar from "@pages/user/myAccount/accountHome/settingSidebar";
import SettingEnterprise from "@pages/user/myAccount/accountHome/settingEnterprise";
import SettingPlain from "@pages/user/myAccount/accountHome/settingPlain";
import SettingModal from "@pages/user/myAccount/accountHome/settingModal";
import BillingBasic from "@pages/user/myAccount/billing/billingBasic";
import BillingEnterprise from "@pages/user/myAccount/billing/billingEnterprise";
import BillingPlan from "@pages/user/myAccount/billing/billingPlan";
import BillingHistory from "@pages/user/myAccount/billing/billingHistory";
import GetStartedSecurity from "@pages/user/myAccount/security/started";
import Overview from "@pages/user/myAccount/security/overview";
import AllowIpAddresses from "@pages/user/myAccount/security/allowIpAdrdresses";
import PrivacySetting from "@pages/user/myAccount/security/privacySetting";
import DeviceManagament from "@pages/user/myAccount/security/deviceManagement";
import BackupRecovery from "@pages/user/myAccount/security/backupRecovery";
import CurrentSessions from "@pages/user/myAccount/security/currentSessions";
import SecurityLog from "@pages/user/myAccount/security/securityLog";
import TeamStarter from "@pages/user/myAccount/membersRoles/teamStarter";
import TeamsMembers from "@pages/user/myAccount/membersRoles/teams";
import TeamInfo from "@pages/user/myAccount/membersRoles/teamInfo";
import MemberStarter from "@pages/user/myAccount/membersRoles/memberStarter";
import TeamMembers from "@pages/user/myAccount/membersRoles/teamMembers";
import ImportantMember from "@pages/user/myAccount/membersRoles/importantmember";
import Roles from "@pages/user/myAccount/membersRoles/roles";
import PermissionsCheck from "@pages/user/myAccount/membersRoles/permissonsCheck";
import PermissionsToggle from "@pages/user/myAccount/membersRoles/permissionsToggle";
import Integrations from "@pages/user/myAccount/integrations";
import Notifications from "@pages/user/myAccount/notifications";
import ApiKeys from "@pages/user/myAccount/apiKeys";
import Appearance from "@pages/user/myAccount/appearance";
import InviteFriend from "@pages/user/myAccount/inviteFriend";
import MyAccountActivity from "@pages/user/myAccount/activity";
import NetworkStarted from "@pages/user/network/started";
import MiniCards from "@pages/user/network/userCards/miniCards";
import TeamCrew from "@pages/user/network/userCards/teamCrew";
import Author from "@pages/user/network/userCards/author";
import Social from "@pages/user/network/userCards/social";
import NFTNetwork from "@pages/user/network/userCards/nft";
import TeamCrewUserBase from "@pages/user/network/userTable/teamCrew";
import AppRoster from "@pages/user/network/userTable/appRoster";
import MarketAuthors from "@pages/user/network/userTable/marketAuthors";
import SaasUsers from "@pages/user/network/userTable/saasUser";
import StoreClients from "@pages/user/network/userTable/storeClients";
import Visitors from "@pages/user/network/userTable/visitors";
import SignIn from "@pages/user/authentication/classic/signIn";
import SignUp from "@pages/user/authentication/classic/signUp";
import TwoFA from "@pages/user/authentication/classic/twoFA";
import CheckMail from "@pages/user/authentication/classic/checkMail";
import EnterEmail from "@pages/user/authentication/classic/resetPassword/enterEmail";
import CheckEmail from "@pages/user/authentication/classic/resetPassword/checkEmail";
import ResetPassword from "@pages/user/authentication/classic/resetPassword/resetPassword";
import PasswordChanged from "@pages/user/authentication/classic/resetPassword/passwordChanges";
import BrandedSignIn from "@pages/user/authentication/branded/signIn";
import BrandedSignUp from "@pages/user/authentication/branded/signUp";
import BrandedTwoFA from "@pages/user/authentication/branded/twoFA";
import BrandedCheckEmail from "@pages/user/authentication/branded/checkEmail";
import BrandedEnterEmail from "@pages/user/authentication/branded/resetPassword/enterEmail";
import BrandedResetCheckEmail from "@pages/user/authentication/branded/resetPassword/checkEmail";
import BrandedResetPassword from "@pages/user/authentication/branded/resetPassword/resetPassword";
import BrandedChangedPassword from "@pages/user/authentication/branded/resetPassword/changedPassword";
import Error404 from "@pages/user/authentication/error404";
import Error500 from "@pages/user/authentication/error500";
import WelcomeModal from "@pages/user/authentication/welcome";
import AccountDeactivatedModal from "@pages/user/authentication/accountDeactivated";


import '../globals.css'

const Router = () => {

    return (
        <>
            <Routes>
                <Route path='/' element={<Dashboard />}></Route>
                <Route path='/user/publicProfiles/profiles/default' element={<Default />}></Route>
                <Route path='/user/publicProfiles/profiles/creator' element={<Creator />}></Route>
                <Route path='/user/publicProfiles/profiles/company' element={<Company />}></Route>
                <Route path='/user/publicProfiles/profiles/nft' element={<NFT />}></Route>
                <Route path='/user/publicProfiles/profiles/blogger' element={<Blogger />}></Route>
                <Route path='/user/publicProfiles/profiles/crm' element={<CRM />}></Route>
                <Route path='/user/publicProfiles/profiles/gamer' element={<Gamer />}></Route>
                <Route path='/user/publicProfiles/profiles/feeds' element={<Feeds />}></Route>
                <Route path='/user/publicProfiles/profiles/plain' element={<Plain />}></Route>
                <Route path='/user/publicProfiles/profiles/modal' element={<Modal />}></Route>
                <Route path='/user/publicProfiles/works' element={<Works />}></Route>
                <Route path='/user/publicProfiles/teams' element={<Teams />}></Route>
                <Route path='/user/publicProfiles/network' element={<Network />}></Route>
                <Route path='/user/publicProfiles/activity' element={<Activity />}></Route>
                <Route path='/user/publicProfiles/campaigns' element={<Campaigns />}></Route>
                <Route path='/user/publicProfiles/empty' element={<Empty />}></Route>
                <Route path='/user/publicProfiles/projects/column-3' element={<ThreeColumns />}></Route>
                <Route path='/user/publicProfiles/projects/column-2' element={<TwoColumns />}></Route>
                <Route path='/user/myAccount/accountHome/get-started' element={<GetStarted />}></Route>
                <Route path='/user/myAccount/accountHome/user-profile' element={<UserProfile />}></Route>
                <Route path='/user/myAccount/accountHome/company-profile' element={<CompanyProfile />}></Route>
                <Route path='/user/myAccount/accountHome/setting-sidebar' element={<SettingSidebar />}></Route>
                <Route path='/user/myAccount/accountHome/setting-enterprise' element={<SettingEnterprise />}></Route>
                <Route path='/user/myAccount/accountHome/setting-plain' element={<SettingPlain />}></Route>
                <Route path='/user/myAccount/accountHome/setting-modal' element={<SettingModal />}></Route>
                <Route path='/user/myAccount/billing/billing-basic' element={<BillingBasic />}></Route>
                <Route path='/user/myAccount/billing/billing-enterprise' element={<BillingEnterprise />}></Route>
                <Route path='/user/myAccount/billing/billing-plans' element={<BillingPlan />}></Route>
                <Route path='/user/myAccount/billing/billing-history' element={<BillingHistory />}></Route>
                <Route path='/user/myAccount/security/get-started' element={<GetStartedSecurity />}></Route>
                <Route path='/user/myAccount/security/overview' element={<Overview />}></Route>
                <Route path='/user/myAccount/security/allowed-ip-addresses' element={<AllowIpAddresses />}></Route>
                <Route path='/user/myAccount/security/privacy-setting' element={<PrivacySetting />}></Route>
                <Route path='/user/myAccount/security/device-managament' element={<DeviceManagament />}></Route>
                <Route path='/user/myAccount/security/backup-recovery' element={<BackupRecovery />}></Route>
                <Route path='/user/myAccount/security/current-sessions' element={<CurrentSessions />}></Route>
                <Route path='/user/myAccount/security/log' element={<SecurityLog />}></Route>
                <Route path='/user/myAccount/members/team-starter' element={<TeamStarter />}></Route>
                <Route path='/user/myAccount/members/teams' element={<TeamsMembers />}></Route>
                <Route path='/user/myAccount/members/team-info' element={<TeamInfo />}></Route>
                <Route path='/user/myAccount/members/member-starter' element={<MemberStarter />}></Route>
                <Route path='/user/myAccount/members/team-members' element={<TeamMembers />}></Route>
                <Route path='/user/myAccount/members/import-member' element={<ImportantMember />}></Route>
                <Route path='/user/myAccount/members/roles' element={<Roles />}></Route>
                <Route path='/user/myAccount/members/permissions-toggle' element={<PermissionsToggle />}></Route>
                <Route path='/user/myAccount/members/permissions-check' element={<PermissionsCheck />}></Route>
                <Route path='/user/myAccount/integrations' element={<Integrations />}></Route>
                <Route path='/user/myAccount/notifications' element={<Notifications />}></Route>
                <Route path='/user/myAccount/api-keys' element={<ApiKeys />}></Route>
                <Route path='/user/myAccount/appearance' element={<Appearance />}></Route>
                <Route path='/user/myAccount/invite-friend' element={<InviteFriend />}></Route>
                <Route path='/user/myAccount/activity' element={<MyAccountActivity />}></Route>
                <Route path='/user/network/started' element={<NetworkStarted />}></Route>
                <Route path='/user/network/userCard/mini-cards' element={<MiniCards />}></Route>
                <Route path='/user/network/userCard/team-crew' element={<TeamCrew />}></Route>
                <Route path='/user/network/userCard/author' element={<Author />}></Route>
                <Route path='/user/network/userCard/social' element={<Social />}></Route>
                <Route path='/user/network/userCard/nft' element={<NFTNetwork />}></Route>
                <Route path='/user/network/userTable/team-crew' element={<TeamCrewUserBase />}></Route>
                <Route path='/user/network/userTable/app-roster' element={<AppRoster />}></Route>
                <Route path='/user/network/userTable/market-authors' element={<MarketAuthors />}></Route>
                <Route path='/user/network/userTable/saas-users' element={<SaasUsers />}></Route>
                <Route path='/user/network/userTable/store-clients' element={<StoreClients />}></Route>
                <Route path='/user/network/userTable/visitors' element={<Visitors />}></Route>
                <Route path='/user/authentication/classic/sign-in' element={<SignIn />}></Route>
                <Route path='/user/authentication/classic/sign-up' element={<SignUp />}></Route>
                <Route path='/user/authentication/classic/2-fA' element={<TwoFA />}></Route>
                <Route path='/user/authentication/classic/check-mail' element={<CheckMail />}></Route>
                <Route path='/user/authentication/classic/resetPassword/enter-email' element={<EnterEmail />}></Route>
                <Route path='/user/authentication/classic/resetPassword/check-email' element={<CheckEmail />}></Route>
                <Route path='/user/authentication/classic/resetPassword/password-change' element={<ResetPassword />}></Route>
                <Route path='/user/authentication/classic/resetPassword/password-changed' element={<PasswordChanged />}></Route>
                <Route path='/user/authentication/branded/sign-in' element={<BrandedSignIn />}></Route>
                <Route path='/user/authentication/branded/sign-up' element={<BrandedSignUp />}></Route>
                <Route path='/user/authentication/branded/2-FA' element={<BrandedTwoFA />}></Route>
                <Route path='/user/authentication/branded/check-email' element={<BrandedCheckEmail />}></Route>
                <Route path='/user/authentication/branded/resetPassword/enter-email' element={<BrandedEnterEmail />}></Route>
                <Route path='/user/authentication/branded/resetPassword/check-email' element={<BrandedResetCheckEmail />}></Route>
                <Route path='/user/authentication/branded/resetPassword/password-change' element={<BrandedResetPassword />}></Route>
                <Route path='/user/authentication/branded/resetPassword/password-changed' element={<BrandedChangedPassword />}></Route>
                <Route path='/user/authentication/error-404' element={<Error404 />}></Route>
                <Route path='/user/authentication/error-500' element={<Error500 />}></Route>
                <Route path='/user/authentication/welcome-message' element={<WelcomeModal />}></Route>
                <Route path='/user/authentication/account-deactivated' element={<AccountDeactivatedModal />}></Route>

            </Routes>
        </>
    );
}

export default Router;